ai:
  prompt-max-length: 4000
  openai:
    base-url: https://api.openai.com
    api-key: ${OPENAI_API_KEY}
    model: ${OPEN_API_MODEL:gpt-4o-mini}
    chat-path: /v1/chat/completions


spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:proposal-ai-consumer-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      topic: ${KAFKA_PRODUCER_TOPIC:new-ai-proposal}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8083